name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Usar Node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instalar dependências do Nuxt
      - name: Install dependencies
        run: |
          cd clubeo_app
          npm install

      # 4. Gerar site estático
      - name: Generate Nuxt static site
        run: |
          cd clubeo_app
          npm run generate

      # 5. Deploy NUXT
      - name: FTP Deploy Nuxt
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./clubeo_app/.output/public/
          server-dir: /

      # 6. Deploy PHP API
      - name: FTP Deploy PHP API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./clubeo_php_api/
          server-dir: /clubeo_php_api/
